### ISSUE TITLE
Light menu bar,  scroll bar even with dark mode enabled.

### ISSUE THREAD

**Issue by amit9838** [advaithm/NightPDF#10]
![image](https://user-images.githubusercontent.com/61614402/207951454-0d29a67d-83ae-483e-b5e3-a0d5554adc5f.png)

I didn't found any way to fix this. Would be great if you add theaming option.

**Comment by Lunarequest** [comment]
It seems as if you are using windows in light from the screenshot. Theres no way to override this in electron

**Comment by amit9838** [comment]
I'm using fedora 37

**Comment by Lunarequest** [comment]
Do you have a gtk3 theme set? Its outside electrons control

**Comment by amit9838** [comment]
yes,  other application based on gtk 3 are using dark theme
![image](https://user-images.githubusercontent.com/61614402/208237237-a57826bd-8a4b-440a-b088-ea04712fd4e2.png)
