### ISSUE TITLE
Update Flathub Version?

### ISSUE THREAD

**Issue by Squallsoldier** [advaithm/NightPDF#13]
Hello! luv this app, can you guys please update the flathub version?..

Thank you!

**Comment by Lunarequest** [comment]
just working on a few quick updates(mostly related to reducing the bundle size) I'd like to hold off just for a little  bit till i'm done with that

**Comment by Squallsoldier** [comment]
understood, take your time, this is my new favorite pdf reader!

Thanks!

**Comment by Lunarequest** [comment]
yup just cut the release with the smaller size working on the flatpak

**Comment by Lunarequest** [comment]
https://github.com/flathub/io.github.lunarequest.NightPDF/pull/4 done!
