### ISSUE TITLE
No Win release since v1.0.5

### ISSUE THREAD

**Issue by olsonperrensen** [advaithm/NightPDF#15]
Where are the binaries for windows? What is the minimum NT 6.x version to run it?

**Comment by Lunarequest** [comment]
I don't have a windows machine and CI has broken, if you are able to fix the CI it should just work, I've been building so far using windows 2019

**Comment by Lunarequest** [comment]
I believe there is some sort of issue with electron-builder

**Comment by Lunarequest** [comment]
@olsonperrensen I have resolved the issue more info in the release notes
