### ISSUE TITLE
Install the app per machine (for all users)

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#17]
Hi,
I want to install the app for all users to %ProgramFiles% instead of %LocalAppData%
Like the Simplenote app:
![image](https://user-images.githubusercontent.com/23485114/183217756-a16527c4-730a-4237-9b3d-72f3336a719b.png)

**Comment by Lunarequest** [comment]
should be fixed in v1.2.2

**Comment by xmha97** [comment]
Thanks

**Comment by xmha97** [comment]
@Lunarequest Thanks, but now installing it only for for all users.
Please add installation option for current user and all users.

**Comment by Lunarequest** [comment]
currently building a release in theory this should work, electron-builder on windows is something i can't test https://github.com/Lunarequest/NightPDF/releases/tag/v1.2.3

**Comment by xmha97** [comment]
> Currently building a release in theory this should work, electron-builder on Windows is something I can't test https://github.com/Lunarequest/NightPDF/releases/tag/v1.2.3

Thanks 🙏

![image](https://user-images.githubusercontent.com/23485114/235028142-46f1af13-41d1-423a-a3b9-ceeacb6b292f.png)

**Comment by Lunarequest** [comment]
Yay!
