### ISSUE TITLE
Command Line

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#18]
Hi,
I want to open a specific page from a PDF file in this app.

On Adobe Acrobat Reader/Pro, it's possible:
```
"%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Acrobat.exe" /A "page=7" "C:\Program Files\Adobe\Acrobat DC\Acrobat\plug_ins\Annotations\Stamps\ENU\Standard.pdf"
```

Also all browser support this feature:
http://www.pdf995.com/samples/pdf.pdf#page=3.pdf

Please add this feature to this app.

**Comment by Lunarequest** [comment]
added in v1.2.2

**Comment by xmha97** [comment]
Thanks

**Comment by xmha97** [comment]
@Lunarequest Thanks, what's the app command lines?
Write on README file.

**Comment by Lunarequest** [comment]
@xmha97 done

**Comment by xmha97** [comment]
Thanks 🙏
