### ISSUE TITLE
Improve the app icon

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#19]
Hi, please improve the app icon.
To do this, open the icon with the [Greenfish Icon Editor Pro](https://greenfishsoftware.org/gfie.php) app on Linux or Windows.
1. As you can see, the icons are sorted in ascending order, that is, the smallest icon is at the top of the list and the largest icon is at the bottom of the list. This may seem trivial at first glance, but there is a bug in Windows that sometimes uses the first icon in the ICO file, regardless of the size of the icons, and this causes a small icon to be enlarged and finally, the poor-quality icon will be displayed.
**So the icons should be arranged in descending order.**
![image](https://user-images.githubusercontent.com/23485114/235016608-d2172a07-a50a-46c5-a3c1-91a8748f0101.png)

2. A Windows icon should include the following sizes:
`256x256`, `64x64`, `48x48`, `40x40`, `32x32`, `24x24`, `20x20`, and `16x16`
(All default Windows icons follow this rule)
You have put sizes `192x192`, `128x128`, and `96x96` in your icon, which is useless, and you have not put sizes `16x16`, `20x20`, `24x24`, `32x32`, and `40x40`, which are used in Windows.
![image](https://user-images.githubusercontent.com/23485114/235016294-89d28c9e-8490-4b00-b884-c1e7a504fc02.png)

Instead of creating an issue, I wanted to create a PR but I couldn't find the SVG icon (the mipmap should be created from a vector file, not just a resized picture)

(Sorry for my bad English)
Thanks. 🙏

**Comment by Lunarequest** [comment]
So the icon svg needs a bit of a history lesson. Back in yr old days of 2019 this repo was a fork of the original nightpdf. I was one of the more active contributors adding intial linux builds and fixing various bugs. At one point the original repo was archive.

I took up maintaining this fork with the blessing of the og dev, fixing various bugs upgrading electron(11 to 12 was so painful lol). At some point after the cryptocrash the og creator a self proclaimed "cryptobro" deleted every single one of his accounts i was aware of. He is the only one who would have the raw image(iirc he might have actually lost it). I'm not good at art/icon design so i've never made a new one but would be open too

**Comment by Lunarequest** [comment]
I've reorder the ico file uisng gimp, however I will be looking into getting a new icon

**Comment by xmha97** [comment]
> I've reorder the ico file uisng gimp, however I will be looking into getting a new icon

@Lunarequest Thanks for reorder the ICO file.
Please add `16x16`, `20x20`, `24x24`, `32x32`, and `40x40`.
These sizes are required for Windows.
