### ISSUE TITLE
Keyboard shortcuts for tab support feature.

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#23]
Thank you for supporting tab.
Please add keyboard shortcuts:

| Command                     | Shortcut                       |
|-----------------------------|--------------------------------|
| **Go one Tab to the Right** | **`Ctrl` + `Tab`**             |
| **Go one Tab to the Left**  | **`Ctrl` + `Shift` + `Tab`**   |
| **New Tab**                 | **`Ctrl` + `T`**               |
| **Close Tab**               | **`Ctrl` + `W`**               |
| **Close Tab**               | **`Ctrl` + `F4`**              |
| Go one Tab to the Right     | `Ctrl` + `Page Down`           |
| Go one Tab to the Left      | `Ctrl` + `Page Up`             |
| Go to Tab 1                 | `Ctrl` + `1`                   |
| Go to Tab 2                 | `Ctrl` + `2`                   |
| Go to Tab 3                 | `Ctrl` + `3`                   |
| Go to Tab 4                 | `Ctrl` + `4`                   |
| Go to Tab 5                 | `Ctrl` + `5`                   |
| Go to Tab 6                 | `Ctrl` + `6`                   |
| Go to Tab 7                 | `Ctrl` + `7`                   |
| Go to Tab 8                 | `Ctrl` + `8`                   |
| Go to Last Tab              | `Ctrl` + `9`                   |
| Undo Close Tab              | `Ctrl` + `Shift` + `T`         |
| Move Tab Left               | `Ctrl` + `Shift` + `Page Up`   |
| Move Tab Right              | `Ctrl` + `Shift` + `Page Down` |
| Move Tab to start           | `Ctrl` + `Shift` + `Home`      |
| Move Tab to end             | `Ctrl` + `Shift` + `End`       |

Thanks.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
@Lunarequest @zeyus Please release a new version.

**Comment by Lunarequest** [comment]
I need some time but i will!
(note zeyus doesn't have permission to release you shouldn't ping them)
