### ISSUE TITLE
Dark scrollbar like Firefox

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#28]
Please use the dark scrollbar like Firefox.

# NightPDF
![image](https://github.com/Lunarequest/NightPDF/assets/23485114/24fd4879-9585-416b-9b9c-18cdc1c96ba1)

# Firefox
![image](https://github.com/Lunarequest/NightPDF/assets/23485114/01327a29-42a1-4176-8098-3d56e94468e7)

Thanks.

**Comment by zeyus** [comment]
This should be addressed in https://github.com/Lunarequest/NightPDF/pull/24

**Comment by zeyus** [comment]
New scrollbar style: 
<img width="112" alt="image" src="https://github.com/Lunarequest/NightPDF/assets/75656/ffdfab97-3209-44c2-9a2a-bc859a26a565">

**Comment by xmha97** [comment]
> New scrollbar style: 
> <img width="112" alt="image" src="https://github.com/Lunarequest/NightPDF/assets/75656/ffdfab97-3209-44c2-9a2a-bc859a26a565">
> 

Wow thanks.
It's very beautiful.
