### ISSUE TITLE
"Original" button

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#29]
Please add a button to view the original version of the documents. (light mode)

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/e0dc0195-9e4f-4310-9203-81749729f9ae)

The reason I want to add this button is that some images may be negative:

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/a8dd89f8-b3d8-4299-956e-433a25fa5d7d)

**Comment by Lunarequest** [comment]
if you switch to custom by default its the same as no filter
