### ISSUE TITLE
NightPDF open links

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#30]
Hi, NightPDF open links.
Please disable the in-app browser.

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/57e7d0f8-8d88-4678-a963-5382110fb491)

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/9eef2a2d-e07e-451d-87a8-3a11228a2d36)

**Comment by Lunarequest** [comment]
this has been fixed!

**Comment by xmha97** [comment]
Thanks
