### ISSUE TITLE
Capitalize app name

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#31]
Hi, please capitalize the app name. (on Ubuntu Linux)

NightPdf -> NightPDF

![Screenshot from 2023-06-09 13-27-10](https://github.com/Lunarequest/NightPDF/assets/23485114/e17b9a46-9774-4715-a45c-9055eb0442e1)

**Comment by Lunarequest** [comment]
done!

**Comment by xmha97** [comment]
Thanks 🙏
