### ISSUE TITLE
[Linux] [Flathub] Drag and drop does not work!

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#33]
Hi, Drag and Drop does not work!
https://www.dropbox.com/s/soogh7h27wc2j91/2023-06-11%2001-57-07.mp4?dl=1

**Comment by Lunarequest** [comment]
until https://bugs.chromium.org/p/chromium/issues/detail?id=1424845 is added to chromium and https://github.com/electron/electron/issues/30650 is resolved this will actually never work in flatpak
