### ISSUE TITLE
[Linux] [Flathub] The file cannot be opened through OpenWith!

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#34]
Hi, the file cannot be opened through OpenWith!
https://www.dropbox.com/s/soogh7h27wc2j91/2023-06-11%2001-57-07.mp4?dl=1

**Comment by zeyus** [comment]
what happens if you try the "Open with other application" option in the context menu?
<img width="547" alt="image" src="https://github.com/Lunarequest/NightPDF/assets/75656/60cf0ae3-da05-40dc-8d8a-09d60dadf41d">

**Comment by zeyus** [comment]
@xmha97 I added some mimetypes to the desktop file could you try if this build shows up in the context menu?
`flatpak install --user https://dl.flathub.org/build-repo/30975/io.github.lunarequest.NightPDF.flatpakref`
