### ISSUE TITLE
Add "About" item

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#35]
Please add the "About" item to the Help menu.

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/6d6b991a-27fa-412c-9283-9d5be7d82bba)

Now I can't see the installed version.

This feature is on all apps for example VS Code.

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/1d7d7611-6a0c-4cb7-a16f-cfc08ab62663)

![image](https://github.com/Lunarequest/NightPDF/assets/23485114/ed1c4acb-d291-4eed-9551-57b7202fff97)

**Comment by zeyus** [comment]
this should also be addressed in https://github.com/Lunarequest/NightPDF/pull/24 (at least, we will have a settings page with the version info visible)

**Comment by xmha97** [comment]
Thanks, the settings page is great. 👍
