### ISSUE TITLE
[Keyboard shortcuts] ESC: exit the app.

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#37]
Please add a hotkey for the Escape key to close the app. (like Sumatra PDF)
Similar: #23

**Comment by zeyus** [comment]
I don't know what @Lunarequest thinks, but I don't really like having `esc` bound to closing an app. I use it all the time to close dialogs or cancel actions, I don't think it should close an application?

**Comment by Lunarequest** [comment]
I agree with @zeyus its a very bad idea imo

**Comment by xmha97** [comment]
> I don't know what @Lunarequest thinks, but I don't really like having `esc` bound to closing an app. I use it all the time to close dialogs or cancel actions, I don't think it should close an application?

Yes, you are right and you can close this issue.
Now I will use the Alt+F4 keys to close the app.
