### ISSUE TITLE
Open multiple books by tabs

### ISSUE THREAD

**Issue by Insidevk18** [advaithm/NightPDF#4]
I love this PDF viewer, I feel that the only thing missing is the ability to open multiple books by tabs inside the program, since having several minimized program windows takes up too much space on my taskbar.

Thanks for your great work man. :)

**Comment by Lunarequest** [comment]
I would like to document our architecture in case anyone wants to pick this up. I don't really have enough knowledge to implement this. Please note I am not the original author of the application. The original author deleted all their social media after well investing in ... crypto. 

First I will break up the app. There is a main process([app.js](https://github.com/Lunarequest/NightPDF/blob/mistress/app.js)), the preload([preload.js](https://github.com/Lunarequest/NightPDF/blob/mistress/app/preload.js)) and finally the render([index.js](https://github.com/Lunarequest/NightPDF/blob/mistress/app/index.js))

When a user opens a file this occurs in the render process. From this a call using preload is sent to resize the window to the max size. Then a call is made to convert the file path into a the filename. Then the file path is converted into a URL as an argument to [viewer.html](https://github.com/Lunarequest/NightPDF/blob/mistress/app/libs/pdfjs/web/viewer.html) and is set to a iframe. Finally the iframe renders the PDF file along with a css filter being applied on the parent of the iframe.  This makes it very difficult to add a tab system without rewriting everything.

**Comment by Lunarequest** [comment]
I believe https://github.com/brrd/electron-tabs would be very useful if anyone wants to pick this up
