### ISSUE TITLE
NightPDF loads file but can not view it.

### ISSUE THREAD

**Issue by Charlevia** [advaithm/NightPDF#41]
Ubuntu 23.04 Software repository dowload
![NichtPDF](https://github.com/Lunarequest/NightPDF/assets/54204450/4281e4be-5a10-472e-9a8c-2dd75c44273a)

**Comment by Lunarequest** [comment]
Ah it should be fixed in mistress

**Comment by AleMunin** [comment]
Exact same problem here, and just with some PDFs, I wish I could be more specific about it.

Am using Zorin 16.2

**Comment by Lunarequest** [comment]
if you can launch with the env var debug set to 1 and then the output from the debug console inside nightpdf it would be helpful!

**Comment by HighKingofMelons** [comment]
Ran into a similar issue using the latest version from Flathub (2.0.3) on Fedora Silverblue 38

The problem seems to occur when trying to load a file from a file-uri.

This is the debug output when i pass a file as a file-uri and the app fails to load the file:
```
loading
render.mjs:199 TabGroup is ready, moving container
render.mjs:199 Array(1)0: ['file:///run/flatpak/doc/e8bc990e/output.pdf']length: 1[[Prototype]]: Array(0)
render.mjs:199 opening  Array(1)0: "file:///run/flatpak/doc/e8bc990e/output.pdf"length: 1[[Prototype]]: Array(0)
render.mjs:199 No tabs yet, creating new tab
render.mjs:199 Array(1)0: "file:///run/flatpak/doc/e8bc990e/output.pdf"length: 1[[Prototype]]: Array(0)
render.mjs:199 tab loaded
render.mjs:199 inserted style 1
```

And this is the same file in the same location but passed using a path:
```
loading
render.mjs:199 TabGroup is ready, moving container
render.mjs:199 Array(1)0: ['/run/flatpak/doc/e8bc990e/output.pdf']length: 1[[Prototype]]: Array(0)
render.mjs:199 opening  Array(1)0: "/run/flatpak/doc/e8bc990e/output.pdf"length: 1[[Prototype]]: Array(0)
render.mjs:199 No tabs yet, creating new tab
render.mjs:199 Array(1)0: "/run/flatpak/doc/e8bc990e/output.pdf"length: 1[[Prototype]]: Array(0)
render.mjs:199 tab loaded
render.mjs:199 inserted style 1
```
This one loads correctly.

A similar thing also happens when you provide the app with a non-existent file:
```
loading
render.mjs:199 TabGroup is ready, moving container
render.mjs:199 Array(1)0: ['/fake/path/isnt/real.pdf']length: 1[[Prototype]]: Array(0)
render.mjs:199 opening  Array(1)0: "/fake/path/isnt/real.pdf"length: 1[[Prototype]]: Array(0)
render.mjs:199 No tabs yet, creating new tab
render.mjs:199 Array(1)0: "/fake/path/isnt/real.pdf"length: 1[[Prototype]]: Array(0)
render.mjs:199 tab loaded
render.mjs:199 inserted style 1
```
This one also has the same behaviour as the first example.

**Comment by Lunarequest** [comment]
the issue was the `file://` prefix. filtering this out fixed this issue
