### ISSUE TITLE
Windows 11 preventing NightPDF from running

### ISSUE THREAD

**Issue by fallsdevil** [advaithm/NightPDF#46]
I found this interesting software simple to be an alternative to Xodo Reader, however Windows identified the file as _"suspicious"_ I know this is not true, I managed to install it, but unfortunately **I can't open it**, is there any solution for this?

And in case of doubt, I downloaded the file from here and not from anywhere else, but the first page I went to was this one [here](https://flathub.org/apps/io.github.lunarequest.NightPDF).

**Comment by Lunarequest** [comment]
The file is probably marked suspicious due to not being signed. I unfornatley can not sign them due to costs. Regarding the links i'm pretty sure the page is clear that flathub is linux only

**Comment by fallsdevil** [comment]
Thank you, I tested it again and this time it opened, I think I had actually downloaded the file with the wrong extension 😂
