### ISSUE TITLE
typos in README.MD

### ISSUE THREAD

**Issue by imagochan** [advaithm/NightPDF#47]
Here are some small typos I noticed and the correct spelling to use:

It uses Electron but my eyes dont care. -> It uses Electron but my eyes don’t care.

- Tier 1: Linux, garunteed builds and garunteed 100% functionality -> - Tier 1: Linux, guaranteed builds and guaranteed 100% functionality

- Tier 2: Windows, garunteed builds. Functionality is not garunteed -> - Tier 2: Windows, guaranteed builds. Functionality is not guaranteed

- Tier 3: Macos, builds are not garunteed if it breaks fix is not garunteed. -> - Tier 3: Macos, builds are not guaranteed if it breaks fix is not guaranteed.

**Comment by Lunarequest** [comment]
thanks for pointing them out, I've corrected them!
