### ISSUE TITLE
Dark mode for sidebar scrollbar and thumbnails

### ISSUE THREAD

**Issue by xmha97** [advaithm/NightPDF#48]
Hi, now the contents scrollbar is dark.
Please make the sidebar scrollbar dark.
Also please make thumbnails dark.
![image](https://github.com/Lunarequest/NightPDF/assets/23485114/ae1af090-1a1b-4078-9e09-d6af3b981780)
Thanks.

**Comment by Lunarequest** [comment]
it isn't possible it is set by pdf.js and it uses light color bars. can't really do anything
