### ISSUE TITLE
Sidebars miscolored 

### ISSUE THREAD

**Issue by AustinMarstaller** [advaithm/NightPDF#5]
The sidebars do not match the chosen color scheme. 
![1](https://user-images.githubusercontent.com/77550704/192115725-f4874a15-1d52-45ad-ab34-d9d5b4cae70c.png)

**Comment by Lunarequest** [comment]
are you using windows? if so have you set your os theme to dark? chromium follows the os theme and afaik there's no way to force electron to use dark mode.

**Comment by Lunarequest** [comment]
I am mistaken, `nativeTheme.themeSource = 'dark'` can over ride the os theme, I'll push a commit to main fixing this
