### ISSUE TITLE
feature request: don't invert images

### ISSUE THREAD

**Issue by phanirithvij** [advaithm/NightPDF#57]
Is this possible? Something like Enabled with selective inversion of non-image elements (in chrome flags)
I tried it but on chrome it doesn't work with PDF documents.

![Screenshot_20240414_150621](https://github.com/Lunarequest/NightPDF/assets/29627898/4a13d8fe-844e-44b6-a0cf-11790f220f30)

**Comment by TunaFFish** [comment]
+1 for this feature.

When I found NightPDF, I actually expected such a setting.
On Apple devices it is called "smart invert", everything is inverted but not the images.
You can read about it here: https://useyourloaf.com/blog/accessibility-smart-invert/

Here is how it is done in Obsidian:
https://forum.obsidian.md/t/pdf-smart-invert-dont-invert-pictures-while-in-dark-mode/67492

![](https://useyourloaf.com/blog/accessibility-smart-invert/003.png)

**Comment by phanirithvij** [comment]
My workaround was to import the pdf into Google drive and open with google docs. And dark mode.

**Comment by Lunarequest** [comment]
This isn't possible with how we apply dark mode. I'm personally not interested in writing a pdf viewer from scratch just to implement this
