### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Viterzgir** [advaithm/NightPDF#63]
I have an error while building the latest NightPdf-3.0.0-beta4 version
https://paste.ee/p/B5Imz
Attachment Build log from tmp:
[/tmp/xfs-ce52df69/build.log](https://github.com/Lunarequest/NightPDF/files/15474805/build.log)
[/tmp/xfs-e2a7e8ba/build.log](https://github.com/Lunarequest/NightPDF/files/15474829/build.log)
[/tmp/xfs-cbc853cf/build.log](https://github.com/Lunarequest/NightPDF/files/15474878/build.log)
[/tmp/xfs-2c26d40b/build.log](https://github.com/Lunarequest/NightPDF/files/15474861/build.log)
[/tmp/xfs-337be446/build.log](https://github.com/Lunarequest/NightPDF/files/15474877/build.log)

**Comment by Lunarequest** [comment]
I have seen this issue on linux distros where selinux is enabled. this is a limitation of selinux since it tries to unpack and run executables in /tmp. this is strictly forbidden with most selinux configs, can't really offer a solution other then disable selinux
