### ISSUE TITLE
Key bindings conflict with other chromium browsers'

### ISSUE THREAD

**Issue by tom-huntington** [advaithm/NightPDF#65]
I cant:

* switch between tabs with `ctrl+tab` ect.
* open new tab with `ctrl+t`
* reopen previously closed tab with `ctrl+shift+t`

Closing NightPDF will fix this. Opening will reproduce it.

Seems like someone else would notice it. So maybe it's just reproducing on my machine?

**Comment by vsuhas-edu** [comment]
yeah, i've been having this problem too.

**Comment by vsuhas-edu** [comment]
i found a fix, just go to File -> Settings -> Keybinds and remove the conflicting keybinds. Close and reopen the app and you should be good to go.

**Comment by thomasamendoza** [comment]
Experiencing the same issue. NightPDF Version 3.0.0 Beta 4, running on macOS 12.7.5 (21H1222)
