### ISSUE TITLE
Are the random notifications intentional behavior?

### ISSUE THREAD

**Issue by Mrroot3r** [advaithm/NightPDF#66]
Is it normal to get notifications with political statements from this program? People have the right to their own beliefs, but pushing random stuff though notifications is almost malware behavior. especially with the misspelling I am wondering if there is a bad actor here?
![NightPDF](https://github.com/Lunarequest/NightPDF/assets/52358599/d173a33d-45e7-40d4-9435-a66006646d29)

**Comment by Candlemass** [comment]
This dev is not only incompetent but also an ignorant clown that denies biology.

I've seen enough.

Sadly, you won't receive a reply to this hence my ignorant comment.

**Comment by Mrroot3r** [comment]
lol. thanks for the confirmation. silence says a lot.
