### ISSUE TITLE
Wayland please please!

### ISSUE THREAD

**Issue by golompiki** [advaithm/NightPDF#69]
Scaling on XWayland is a nightmare. Maybe it is a flatpak packaging error, but I don't thing so. If you do not support native wayland, please consider supporting it.

**Comment by Lunarequest** [comment]
I do not intend to ship NightPDF in flatpak with wayland enabled due to its buggy and work in progress nature. You can force the application to use wayland by using these cli arguments `--enable-features=UseOzonePlatform --ozone-platform=wayland`
