### ISSUE TITLE
What is toggling sidebar initially? Which file is altering PDF.js (viewer.mjs) default settings?

### ISSUE THREAD

**Issue by sudg6** [advaithm/NightPDF#70]
Alternatively, where are the default or initial settings defined?

I want to disable side bar upon opening a new file

**Comment by Lunarequest** [comment]
you can in the general settings toggle this
![image](https://github.com/user-attachments/assets/fb9519f7-2551-4861-9fb5-128b88fc6b36)

**Comment by sudg6** [comment]
@Lunarequest I mean in the source code not in the UI
