### ISSUE TITLE
[Feature Request] Some elementry features

### ISSUE THREAD

**Issue by amit9838** [advaithm/NightPDF#9]
This app is providing all featues that we mostly use,  but it would be more usefull if you can add few more features like -
1. Save Custom presents for backgrounds.
2. Context menus with features like copy, highlight, etc.
3. Meaning lookup.
4. Better theme support (Great if GTK4).
5. Eraser , Undo , Redo.

Thanks for beautiful app.

**Comment by Obsidian-user** [comment]
I also would really appreciate feature request 1

Thanks for all your hard work!

**Comment by Lunarequest** [comment]
so 1 isn't possible since we use mozzila's pdf veiwer.
2 should be possible to implement 
3 might be but again we use mozzila's pdf viewer
4 just isn't. electron handles themeing. and honestly GTK 4 themeing sucks since on anything not gnome it doesn't gel with the system
5. read 1 
6

**Comment by Obsidian-user** [comment]
Thanks for the quick response @Lunarequest . I completely trust what you are saying, as you're the expert. I'm not very IT literate but could you please help me understand if the idea below could be a possible solution for request 1?

If someone really wanted a certain colour profile for their PDFs, could they adjust the settings in the raw code and recompile it? Perhaps I am missing something, but wouldn't you have had to specify the parameters for the default option?

Again, excuse me if this is an ignorant question 😅

Once again, huge thank you for your work!
